LastROMFolder = "C:/Users/valer/Downloads/New Super Mario Bros. (Europe) (EnFrDeEsIt)"
UITheme = ""
RecentROM = [
    "C:/Users/valer/Downloads/melonDS/Solatorobo - Red the Hunter (Europe) (En,Fr,De,Es,It) (NDSi Enhanced).nds",
    "C:/Users/valer/AppData/Local/Temp/Rar$DRa5552.12854.rartemp/SimCity DS (Europe) (En,Fr,De,Es,It,Nl).nds",
    "C:/Users/valer/AppData/Local/Temp/Rar$DRa10112.3215.rartemp/Itadaki Street DS - Dragon Quest Super Mario (Japan) (English Patched).nds",
    "C:/Users/valer/Downloads/New Super Mario Bros. (Europe) (EnFrDeEsIt)/New Super Mario Bros..nds",
    "C:/Users/valer/Downloads/New Super Mario Bros. (Europe) (EnFrDeEsIt)/New Super Mario Bros. (Europe) (En,Fr,De,Es,It).nds",
    "C:/Users/valer/Downloads/Yoshis Island DS (Europe) (EnFrDeEsIt)/Yoshi's Island DS (Europe) (En,Fr,De,Es,It).nds",
]
FastForwardFPS = 1000.0
PauseLostFocus = false
AudioSync = false
TargetFPS = 60.0
LimitFPS = true
SlowmoFPS = 30.0

[DSi]
NANDPath = ""

[DSi.Camera1]
DeviceName = ""
ImagePath = ""
InputType = 0
XFlip = false

[DSi.Camera0]
DeviceName = ""
ImagePath = ""
InputType = 0
XFlip = false

[DLDI]
Enable = false

[Mouse]
Hide = false
HideSeconds = 5

[Audio]
Interpolation = 0
BitDepth = 0

[Instance0]
EnableCheats = false
SaveFilePath = ""
JoystickID = 0
SavestatePath = ""
CheatFilePath = ""

[Instance0.RTC]
Offset = 0

[Instance0.Gdb]
Enabled = false

[Instance0.Gdb.ARM9]
BreakOnStartup = false
Port = 3333

[Instance0.Gdb.ARM7]
BreakOnStartup = false
Port = 3334

[Instance0.Window2]
Enabled = false

[Instance0.Keyboard]
X = -1
Up = -1
HK_FrameLimitToggle = -1
HK_GuitarGripYellow = -1
A = -1
HK_FrameStep = -1
Y = -1
HK_SlowMoToggle = -1
HK_FastForwardToggle = -1
HK_VolumeDown = -1
HK_GuitarGripBlue = -1
HK_Reset = -1
HK_PowerButton = -1
HK_Mic = -1
HK_SolarSensorIncrease = -1
HK_GuitarGripRed = -1
L = -1
R = -1
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_Pause = -1
Right = -1
Start = -1
Select = -1
HK_FastForward = -1
Left = -1
HK_SwapScreens = -1
HK_SwapScreenEmphasis = -1
Down = -1
B = -1
HK_Lid = -1
HK_SolarSensorDecrease = -1
HK_VolumeUp = -1
HK_GuitarGripGreen = -1

[Instance0.Joystick]
X = -1
Up = -1
HK_FrameLimitToggle = -1
HK_GuitarGripYellow = -1
A = -1
HK_FrameStep = -1
Y = -1
HK_SlowMoToggle = -1
HK_FastForwardToggle = -1
HK_VolumeDown = -1
HK_GuitarGripBlue = -1
HK_Reset = -1
HK_PowerButton = -1
HK_Mic = -1
HK_SolarSensorIncrease = -1
HK_GuitarGripRed = -1
L = -1
R = -1
HK_FullscreenToggle = -1
HK_SlowMo = -1
HK_Pause = -1
Right = -1
Start = -1
Select = -1
HK_FastForward = -1
Left = -1
HK_SwapScreens = -1
HK_SwapScreenEmphasis = -1
Down = -1
B = -1
HK_Lid = -1
HK_SolarSensorDecrease = -1
HK_VolumeUp = -1
HK_GuitarGripGreen = -1

[Instance0.Audio]
DSiVolumeSync = false
Volume = 256

[Instance0.Window0]
Enabled = true
ScreenFilter = false
ScreenAspectTop = 0
IntegerScaling = false
ScreenSizing = 0
ScreenSwap = false
ScreenGap = 0
ScreenAspectBot = 0
ScreenRotation = 0
ScreenLayout = 0
Geometry = "AdnQywADAAAAAAAAAAAAIAAAB38AAAQ3AAACgAAAAUAAAAN/AAAC1QAAAAACAAAAB4AAAAAAAAAAPwAAB38AAAQ3"
ShowOSD = true

[Instance0.Window3]
Enabled = false

[Instance0.DS]
[Instance0.DS.Battery]
LevelOkay = true

[Instance0.Firmware]
MAC = ""
Message = ""
BirthdayDay = 1
BirthdayMonth = 1
FavouriteColour = 0
Language = 1
Username = "melonDS"

[Instance0.Window1]
Enabled = false

[3D]
Renderer = 0

[3D.Soft]
Threaded = true

[Savestate]
RelocSRAM = false

[Emu]
DirectBoot = true
ExternalBIOSEnable = false
ConsoleType = 0

[MP]
AudioMode = 1
RecvTimeout = 25

[LAN]
DirectMode = false

[JIT]
Enable = false
FastMemory = true
BranchOptimisations = true
LiteralOptimisations = true
MaxBlockSize = 32

[Screen]
UseGL = false

[Mic]
WavPath = ""
Device = ""
InputType = 1

